# Generated by Django 3.2.7 on 2021-09-28 01:54

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('account_type', models.IntegerField(choices=[(0, 'Superuser'), (1, 'Monitor'), (2, 'Recruiter'), (3, 'Worker')], default=None)),
            ],
        ),
    ]
